package com.rivetlogic.microsite.action.startup;

import com.liferay.portal.kernel.events.SimpleAction;
import com.liferay.portal.kernel.events.ActionException;
import com.liferay.counter.service.CounterLocalServiceUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.model.Role;
import com.liferay.portal.model.RoleConstants;
import com.liferay.portal.service.ClassNameLocalServiceUtil;
import com.liferay.portal.service.RoleLocalServiceUtil;
import com.liferay.portal.service.UserLocalServiceUtil;
import com.liferay.portal.util.PortalUtil;

import java.util.Date;

public class MicrositeRoleDefinitionAction extends SimpleAction {
	/* (non-Java-doc)
	 * @see com.liferay.portal.kernel.events.SimpleAction#SimpleAction()
	 */
	public MicrositeRoleDefinitionAction() {
		super();
	}

	/* (non-Java-doc)
	 * @see com.liferay.portal.kernel.events.SimpleAction#run(String[] arg0)
	 */
	public void run(String[] arg0) throws ActionException {
		Long defaultCompanyId = PortalUtil.getDefaultCompanyId();
		Role role = null;
		try {
			role = RoleLocalServiceUtil.getRole(defaultCompanyId, ROLE);

		} catch (Exception e) {

			_log.info("Missing Role: " + ROLE + " " + e.getMessage());

		}

		if (Validator.isNull(role)) {
			
			_log.info("Creating Role: " + ROLE);
			
			try {
				
				
				Date now = new Date();
				Long defaultUserId = UserLocalServiceUtil.getDefaultUserId(defaultCompanyId);
				Long roleClassNameId = ClassNameLocalServiceUtil.getClassNameId(Role.class);
				
				long roleId = CounterLocalServiceUtil.increment(Role.class.getName());

				Role suggestionManagerRole = RoleLocalServiceUtil.createRole(roleId);
				
				suggestionManagerRole.setName(ROLE);
				suggestionManagerRole.setTitle("Microsite Requests Manager");
				suggestionManagerRole.setDescription("Autogenerated role from Microsite portlet");
				suggestionManagerRole.setType(RoleConstants.TYPE_REGULAR);
				suggestionManagerRole.setUserId(defaultUserId);
				suggestionManagerRole.setCompanyId(defaultCompanyId);
				suggestionManagerRole.setClassNameId(roleClassNameId);
				suggestionManagerRole.setClassPK(roleId);
				suggestionManagerRole.setCreateDate(now);
				suggestionManagerRole.setModifiedDate(now);

				RoleLocalServiceUtil.addRole(suggestionManagerRole);
				
				_log.info("New Role created: " + ROLE);
				
			} catch (SystemException e) {

				_log.info("Error creating Role: " + ROLE, e);
			} catch ( PortalException e) {
				
				_log.info("Error creating Role: " + ROLE, e);
			}

		}else {
			_log.info("Role "+ ROLE +" already exists.");
		}
	}
	private static final Log _log = LogFactoryUtil.getLog(MicrositeRoleDefinitionAction.class);
	private final static String ROLE = "MICROSITE_REQUESTS_MANAGER"; 
}