/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.microsite.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rivetlogic.microsite.model.MicroSite;
import com.rivetlogic.microsite.model.MicroSiteModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the MicroSite service. Represents a row in the &quot;rivetlogic_micro_site_MicroSite&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rivetlogic.microsite.model.MicroSiteModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MicroSiteImpl}.
 * </p>
 *
 * @author steven.barba
 * @see MicroSiteImpl
 * @see com.rivetlogic.microsite.model.MicroSite
 * @see com.rivetlogic.microsite.model.MicroSiteModel
 * @generated
 */
public class MicroSiteModelImpl extends BaseModelImpl<MicroSite>
	implements MicroSiteModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a micro site model instance should use the {@link com.rivetlogic.microsite.model.MicroSite} interface instead.
	 */
	public static final String TABLE_NAME = "rivetlogic_micro_site_MicroSite";
	public static final Object[][] TABLE_COLUMNS = {
			{ "microSiteId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "groupId", Types.BIGINT },
			{ "siteId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table rivetlogic_micro_site_MicroSite (microSiteId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,groupId LONG,siteId LONG)";
	public static final String TABLE_SQL_DROP = "drop table rivetlogic_micro_site_MicroSite";
	public static final String ORDER_BY_JPQL = " ORDER BY microSite.userId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY rivetlogic_micro_site_MicroSite.userId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rivetlogic.microsite.model.MicroSite"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rivetlogic.microsite.model.MicroSite"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rivetlogic.microsite.model.MicroSite"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long USERID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rivetlogic.microsite.model.MicroSite"));

	public MicroSiteModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _microSiteId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMicroSiteId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _microSiteId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MicroSite.class;
	}

	@Override
	public String getModelClassName() {
		return MicroSite.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("microSiteId", getMicroSiteId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("groupId", getGroupId());
		attributes.put("siteId", getSiteId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long microSiteId = (Long)attributes.get("microSiteId");

		if (microSiteId != null) {
			setMicroSiteId(microSiteId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long siteId = (Long)attributes.get("siteId");

		if (siteId != null) {
			setSiteId(siteId);
		}
	}

	@Override
	public long getMicroSiteId() {
		return _microSiteId;
	}

	@Override
	public void setMicroSiteId(long microSiteId) {
		_microSiteId = microSiteId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask = -1L;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getSiteId() {
		return _siteId;
	}

	@Override
	public void setSiteId(long siteId) {
		_siteId = siteId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			MicroSite.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MicroSite toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MicroSite)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MicroSiteImpl microSiteImpl = new MicroSiteImpl();

		microSiteImpl.setMicroSiteId(getMicroSiteId());
		microSiteImpl.setCompanyId(getCompanyId());
		microSiteImpl.setUserId(getUserId());
		microSiteImpl.setUserName(getUserName());
		microSiteImpl.setCreateDate(getCreateDate());
		microSiteImpl.setModifiedDate(getModifiedDate());
		microSiteImpl.setGroupId(getGroupId());
		microSiteImpl.setSiteId(getSiteId());

		microSiteImpl.resetOriginalValues();

		return microSiteImpl;
	}

	@Override
	public int compareTo(MicroSite microSite) {
		int value = 0;

		if (getUserId() < microSite.getUserId()) {
			value = -1;
		}
		else if (getUserId() > microSite.getUserId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MicroSite)) {
			return false;
		}

		MicroSite microSite = (MicroSite)obj;

		long primaryKey = microSite.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		MicroSiteModelImpl microSiteModelImpl = this;

		microSiteModelImpl._originalCompanyId = microSiteModelImpl._companyId;

		microSiteModelImpl._setOriginalCompanyId = false;

		microSiteModelImpl._originalUserId = microSiteModelImpl._userId;

		microSiteModelImpl._setOriginalUserId = false;

		microSiteModelImpl._originalGroupId = microSiteModelImpl._groupId;

		microSiteModelImpl._setOriginalGroupId = false;

		microSiteModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MicroSite> toCacheModel() {
		MicroSiteCacheModel microSiteCacheModel = new MicroSiteCacheModel();

		microSiteCacheModel.microSiteId = getMicroSiteId();

		microSiteCacheModel.companyId = getCompanyId();

		microSiteCacheModel.userId = getUserId();

		microSiteCacheModel.userName = getUserName();

		String userName = microSiteCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			microSiteCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			microSiteCacheModel.createDate = createDate.getTime();
		}
		else {
			microSiteCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			microSiteCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			microSiteCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		microSiteCacheModel.groupId = getGroupId();

		microSiteCacheModel.siteId = getSiteId();

		return microSiteCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{microSiteId=");
		sb.append(getMicroSiteId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", siteId=");
		sb.append(getSiteId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.rivetlogic.microsite.model.MicroSite");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>microSiteId</column-name><column-value><![CDATA[");
		sb.append(getMicroSiteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>siteId</column-name><column-value><![CDATA[");
		sb.append(getSiteId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = MicroSite.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			MicroSite.class
		};
	private long _microSiteId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _siteId;
	private long _columnBitmask;
	private MicroSite _escapedModel;
}