/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.microsite.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import com.rivetlogic.microsite.model.SiteRequest;
import com.rivetlogic.microsite.service.SiteRequestLocalService;
import com.rivetlogic.microsite.service.persistence.MicroSitePersistence;
import com.rivetlogic.microsite.service.persistence.SiteRequestPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the Site Request local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.rivetlogic.microsite.service.impl.SiteRequestLocalServiceImpl}.
 * </p>
 *
 * @author steven.barba
 * @see com.rivetlogic.microsite.service.impl.SiteRequestLocalServiceImpl
 * @see com.rivetlogic.microsite.service.SiteRequestLocalServiceUtil
 * @generated
 */
public abstract class SiteRequestLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements SiteRequestLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.rivetlogic.microsite.service.SiteRequestLocalServiceUtil} to access the Site Request local service.
	 */

	/**
	 * Adds the Site Request to the database. Also notifies the appropriate model listeners.
	 *
	 * @param siteRequest the Site Request
	 * @return the Site Request that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SiteRequest addSiteRequest(SiteRequest siteRequest)
		throws SystemException {
		siteRequest.setNew(true);

		return siteRequestPersistence.update(siteRequest);
	}

	/**
	 * Creates a new Site Request with the primary key. Does not add the Site Request to the database.
	 *
	 * @param siteRequestId the primary key for the new Site Request
	 * @return the new Site Request
	 */
	@Override
	public SiteRequest createSiteRequest(long siteRequestId) {
		return siteRequestPersistence.create(siteRequestId);
	}

	/**
	 * Deletes the Site Request with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param siteRequestId the primary key of the Site Request
	 * @return the Site Request that was removed
	 * @throws PortalException if a Site Request with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SiteRequest deleteSiteRequest(long siteRequestId)
		throws PortalException, SystemException {
		return siteRequestPersistence.remove(siteRequestId);
	}

	/**
	 * Deletes the Site Request from the database. Also notifies the appropriate model listeners.
	 *
	 * @param siteRequest the Site Request
	 * @return the Site Request that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SiteRequest deleteSiteRequest(SiteRequest siteRequest)
		throws SystemException {
		return siteRequestPersistence.remove(siteRequest);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(SiteRequest.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return siteRequestPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rivetlogic.microsite.model.impl.SiteRequestModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return siteRequestPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rivetlogic.microsite.model.impl.SiteRequestModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return siteRequestPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return siteRequestPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return siteRequestPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public SiteRequest fetchSiteRequest(long siteRequestId)
		throws SystemException {
		return siteRequestPersistence.fetchByPrimaryKey(siteRequestId);
	}

	/**
	 * Returns the Site Request with the primary key.
	 *
	 * @param siteRequestId the primary key of the Site Request
	 * @return the Site Request
	 * @throws PortalException if a Site Request with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public SiteRequest getSiteRequest(long siteRequestId)
		throws PortalException, SystemException {
		return siteRequestPersistence.findByPrimaryKey(siteRequestId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return siteRequestPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the Site Requests.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rivetlogic.microsite.model.impl.SiteRequestModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of Site Requests
	 * @param end the upper bound of the range of Site Requests (not inclusive)
	 * @return the range of Site Requests
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<SiteRequest> getSiteRequests(int start, int end)
		throws SystemException {
		return siteRequestPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of Site Requests.
	 *
	 * @return the number of Site Requests
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getSiteRequestsCount() throws SystemException {
		return siteRequestPersistence.countAll();
	}

	/**
	 * Updates the Site Request in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param siteRequest the Site Request
	 * @return the Site Request that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SiteRequest updateSiteRequest(SiteRequest siteRequest)
		throws SystemException {
		return siteRequestPersistence.update(siteRequest);
	}

	/**
	 * Returns the micro site local service.
	 *
	 * @return the micro site local service
	 */
	public com.rivetlogic.microsite.service.MicroSiteLocalService getMicroSiteLocalService() {
		return microSiteLocalService;
	}

	/**
	 * Sets the micro site local service.
	 *
	 * @param microSiteLocalService the micro site local service
	 */
	public void setMicroSiteLocalService(
		com.rivetlogic.microsite.service.MicroSiteLocalService microSiteLocalService) {
		this.microSiteLocalService = microSiteLocalService;
	}

	/**
	 * Returns the micro site persistence.
	 *
	 * @return the micro site persistence
	 */
	public MicroSitePersistence getMicroSitePersistence() {
		return microSitePersistence;
	}

	/**
	 * Sets the micro site persistence.
	 *
	 * @param microSitePersistence the micro site persistence
	 */
	public void setMicroSitePersistence(
		MicroSitePersistence microSitePersistence) {
		this.microSitePersistence = microSitePersistence;
	}

	/**
	 * Returns the Site Request local service.
	 *
	 * @return the Site Request local service
	 */
	public com.rivetlogic.microsite.service.SiteRequestLocalService getSiteRequestLocalService() {
		return siteRequestLocalService;
	}

	/**
	 * Sets the Site Request local service.
	 *
	 * @param siteRequestLocalService the Site Request local service
	 */
	public void setSiteRequestLocalService(
		com.rivetlogic.microsite.service.SiteRequestLocalService siteRequestLocalService) {
		this.siteRequestLocalService = siteRequestLocalService;
	}

	/**
	 * Returns the Site Request persistence.
	 *
	 * @return the Site Request persistence
	 */
	public SiteRequestPersistence getSiteRequestPersistence() {
		return siteRequestPersistence;
	}

	/**
	 * Sets the Site Request persistence.
	 *
	 * @param siteRequestPersistence the Site Request persistence
	 */
	public void setSiteRequestPersistence(
		SiteRequestPersistence siteRequestPersistence) {
		this.siteRequestPersistence = siteRequestPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.rivetlogic.microsite.model.SiteRequest",
			siteRequestLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.rivetlogic.microsite.model.SiteRequest");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return SiteRequest.class;
	}

	protected String getModelClassName() {
		return SiteRequest.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = siteRequestPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.rivetlogic.microsite.service.MicroSiteLocalService.class)
	protected com.rivetlogic.microsite.service.MicroSiteLocalService microSiteLocalService;
	@BeanReference(type = MicroSitePersistence.class)
	protected MicroSitePersistence microSitePersistence;
	@BeanReference(type = com.rivetlogic.microsite.service.SiteRequestLocalService.class)
	protected com.rivetlogic.microsite.service.SiteRequestLocalService siteRequestLocalService;
	@BeanReference(type = SiteRequestPersistence.class)
	protected SiteRequestPersistence siteRequestPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private SiteRequestLocalServiceClpInvoker _clpInvoker = new SiteRequestLocalServiceClpInvoker();
}